/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PrintingRouteImport } from './routes/printing'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as DistrictsIndexRouteImport } from './routes/districts.index'
import { Route as DistrictsDistrictIdRouteImport } from './routes/districts.$districtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintingRoute = PrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsIndexRoute = DistrictsIndexRouteImport.update({
  id: '/districts/',
  path: '/districts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsDistrictIdRoute = DistrictsDistrictIdRouteImport.update({
  id: '/districts/$districtId',
  path: '/districts/$districtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/inventory': typeof InventoryRoute
  '/printing': typeof PrintingRoute
  '/transit': typeof TransitRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/districts/': typeof DistrictsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/inventory': typeof InventoryRoute
  '/printing': typeof PrintingRoute
  '/transit': typeof TransitRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/districts': typeof DistrictsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/inventory': typeof InventoryRoute
  '/printing': typeof PrintingRoute
  '/transit': typeof TransitRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/districts/': typeof DistrictsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispatch'
    | '/inventory'
    | '/printing'
    | '/transit'
    | '/districts/$districtId'
    | '/districts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispatch'
    | '/inventory'
    | '/printing'
    | '/transit'
    | '/districts/$districtId'
    | '/districts'
  id:
    | '__root__'
    | '/'
    | '/dispatch'
    | '/inventory'
    | '/printing'
    | '/transit'
    | '/districts/$districtId'
    | '/districts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispatchRoute: typeof DispatchRoute
  InventoryRoute: typeof InventoryRoute
  PrintingRoute: typeof PrintingRoute
  TransitRoute: typeof TransitRoute
  DistrictsDistrictIdRoute: typeof DistrictsDistrictIdRoute
  DistrictsIndexRoute: typeof DistrictsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printing': {
      id: '/printing'
      path: '/printing'
      fullPath: '/printing'
      preLoaderRoute: typeof PrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/': {
      id: '/districts/'
      path: '/districts'
      fullPath: '/districts/'
      preLoaderRoute: typeof DistrictsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/$districtId': {
      id: '/districts/$districtId'
      path: '/districts/$districtId'
      fullPath: '/districts/$districtId'
      preLoaderRoute: typeof DistrictsDistrictIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispatchRoute: DispatchRoute,
  InventoryRoute: InventoryRoute,
  PrintingRoute: PrintingRoute,
  TransitRoute: TransitRoute,
  DistrictsDistrictIdRoute: DistrictsDistrictIdRoute,
  DistrictsIndexRoute: DistrictsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
